//
// Created by x0leg on 2/28/16.
//

#ifndef ROS_ADAPTER_REGS_H
#define ROS_ADAPTER_REGS_H

enum Regs {
    LEFT_FRONT_ROTOR_RPS = 20,
    LEFT_REAR_ROTOR_RPS = 21,
    RIGHT_FRONT_ROTOR_RPS = 22,
    RIGHT_REAR_ROTOR_RPS = 23,
    LEFT_FRONT_ROTOR_ROUNDS = 30,
    LEFT_REAR_ROTOR_ROUNDS = 31,
    RIGHT_FRONT_ROTOR_ROUNDS = 32,
    RIGHT_REAR_ROTOR_ROUNDS = 33,
};

#endif //ROS_ADAPTER_REGS_H
